cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/mojtaba/projects/Antares/antares/.waf-1.6.11-30618c54883417962c38f5d395f83584/waflib/Tools/c_config.py", line 445, in run_c_code\n    bld.compile()\n  File "/home/mojtaba/projects/Antares/antares/.waf-1.6.11-30618c54883417962c38f5d395f83584/waflib/Build.py", line 190, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 139951504463696: cxxprogram test.cpp.1.o -> testprog}\n[\'/usr/bin/g++\', \'-Wl,-Bsymbolic-functions\', \'-Wl,-z,relro\', \'test.cpp.1.o\', \'-o\', \'/home/mojtaba/projects/Antares/antares/build/.conf_check_f928e99f5ec2b461eb401d0a7a439d8c/testbuild/testprog\', \'-Wl,-Bstatic\', \'-Wl,-Bdynamic\', \'-L/usr/lib/python2.7/config-x86_64-linux-gnu\', \'-lpython27\']\n'
